version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    style: "%"
    validate: true
  
  json:
    (): playmcp_viewer.config.JSONFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/playmcp-viewer.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

loggers:
  playmcp_viewer:
    level: DEBUG
    handlers: [console]
    propagate: false
  fastmcp:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]